### ISSUE TITLE
Replace build label with build number

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/wcms-front-end#7]
Rather than prompt the user to enter a label, tag builds with the automatically generated build number.

This eliminates concerns about labels which vary only in case, as well as removing the need to delete existing builds and the risk of errors preventing the new label from being assigned.

Releases and tags can still be renamed manually.

**Comment by bryanpizzillo** [comment]
To clarify, this build number would match the Jenkins build number.

**Comment by blairlearn** [comment]
This is addressed in 3d4a279d0ce04f76c904de09e01ad6f7c55dfb69
